#! /bin/sh

prefix="test"
donotruntests=false
recursive=false

handle_args() {
  while getopts "nr" "opt"; do
    case "$opt" in
      n) donotruntests=true;;
      r) recursive=true;;
      *) exit 1;;
    esac
  done
  shift $(($OPTIND - 1))
  if [ $# -ge 1 ]; then
    prefix="$@"
  fi
}

print_pass() {
  :
}

print_fail() {
  sed 's/^/  /'
}

runtest() {
  filename=$1
  dirname=$(dirname "$filename")
  basename=$(basename "$filename")
  cd "$dirname"
  output="$("./$basename" 2>&1)"
  success=$?
  if [ $success -eq 0 ]; then
    print_pass
  else
    echo "$filename"
    echo "$output" | print_fail
  fi
  return $success
}

collecttestnames() {
  if $recursive; then
    maxdepth=""
  else
    maxdepth="-maxdepth 1"
  fi
  find -L . $maxdepth -type f -executable -name "$prefix*" | sort
}

runtests() {
  fail=0

  while read filename; do
    if $donotruntests; then
      echo "$filename"
    else
      (runtest "$filename") || fail=1
    fi
  done

  return $fail
}

main() {
  handle_args "$@"
  collecttestnames | runtests
}

main "$@"
