#! /bin/sh

print_pass() {
  echo -n "p "
}

print_fail() {
  echo -n "f "
}

runtest() {
  filename=$1
  sh "$filename"
  success=$?
  if [ $success -eq 0 ]; then
    print_pass
  else
    print_fail
    fail=1
  fi
  echo "$filename"
}

fail=0

for filename in test*; do
  if [ -d "$filename" ]; then
    continue
  fi
  runtest "$filename"
done

exit $fail
