#! /bin/sh

prefix="test"

handle_args() {
  if [ $# -ge 1 ]; then
    prefix="$@"
  fi
}

print_pass() {
  :
}

print_fail() {
  sed 's/^/  /'
}

runtest() {
  filename=$1
  output="$("$filename" 2>&1)"
  success=$?
  if [ $success -eq 0 ]; then
    print_pass
  else
    echo "$filename"
    echo "$output" | print_fail
  fi
  return $success
}

collecttests() {
  find -L . -maxdepth 1 -type f -name "$prefix*" | sort
}

runtests() {
  fail=0

  while read filename; do
    runtest "$filename" || fail=1
  done

  return $fail
}

main() {
  handle_args "$@"
  collecttests | runtests
}

main "$@"
