#! /bin/sh

runtest() {
  testname=$1
  cd $testname
  echo $testname
  output=$(./runtests)
  exitstatus=$?
  if [ $exitstatus -ne 0 ]; then
    echo "fail: $testname"
    echo "output:"
    echo "$output"
    echo "exitstatus: $exitstatus"
  fi
}

cd tests

for dir in *; do
  (runtest $dir)
done
