#! /bin/sh

runtest() {
  testname=$1
  cd $testname
  output=$(./runtests)
  exitstatus=$?
  if [ $exitstatus -ne 0 ]; then
    echo "================"
    echo "fail: $testname"
    echo "exitstatus: $exitstatus"
    echo "output:"
    echo "----------------"
    echo "$output"
    echo "----------------"
  fi
}

cd tests

for dir in *; do
  if [ ! -d "$dir" ]; then
    continue
  fi
  (runtest $dir)
done
