#! /bin/sh

default_pattern="test"

config_donotruntests=false
config_verbose=false
config_shutdir="shutdir"
config_keep=false
config_split=false
config_quiet=false
config_tail=10
SHUT_PWD="$PWD"

# -----------------------------------------------------------------------------
mktemp_tempdir() {
  config_tempdir="$(mktemp -d --tmpdir shuttempdir.XXX 2> /dev/null)" || {
    echo "error creating tempdir" >&2
    echo "cannot continue" >&2
    return 3
  }
}

cd_tempdir() {
  cd -- "$config_tempdir" > /dev/null 2>&1 || {
    echo "failed changing directory to $config_tempdir" >&2
    echo "cannot continue" >&2
    return 3
  }
}

# -----------------------------------------------------------------------------
configfromargv() {
  # this function expects "$@" as argument
  local arg
  while [ $# -ge 1 ]; do
    arg="$1"
    case "$arg" in
      -d) shift ; config_shutdir="$1" ;;
      -k) config_keep=true ;;
      -n) config_donotruntests=true ;;
      -v) config_verbose=true ;;
      -x) config_split=true ;;
      -q) config_quiet=true ;;
      -t) shift ; config_tail="$1" ;;
      --) shift ; break ;;
      -*) echo "argv error: $1" ; exit 2 ;;
       *) break ;;
    esac
    shift
  done
  local pattern
  for pattern in "$@"; do
    echo "$pattern" >> patterns
  done
}

setup() {
  config_fullshutdir="$(readlink -f "$SHUT_PWD/$config_shutdir")"
  if $config_donotruntests; then
    work_func=printtestnames
  else
    work_func=runtestscatcherror
  fi
  if $config_split; then
    runtestsaveoutput_func=runtestsaveoutputsplit
    printbody_func=printbodysplit
  else
    runtestsaveoutput_func=runtestsaveoutputmerge
    printbody_func=printbodymerge
  fi
  if $config_verbose; then
    printreportpass_func=printreportpass
    printreportfail_func=printreportfail
  elif $config_quiet; then
    printreportpass_func=true
    printreportfail_func=true
  else
    printreportpass_func=true
    printreportfail_func=printreportfail
  fi
}

# -----------------------------------------------------------------------------
collecttestnames() {
  if [ ! -s patterns ]; then
    echo "$default_pattern" > patterns
  fi
  local pattern
  local print="-false"
  while read -r pattern; do
    if [ -f "$SHUT_PWD/$pattern" ]; then
      print="$print -o -type f -executable -path \*/$pattern"
    elif [ -d "$SHUT_PWD/$pattern" ]; then
      print="$print -o -type f -executable -path \*/$pattern/\*"
    else
      print="$print -o -type f -executable -regex .\*/$pattern[^/]\*"
    fi
  done < patterns
  find "$SHUT_PWD" -type d -name "$config_shutdir" -prune -o \
        \( $print \) -printf "./%P\n" | sort > tests
}

# -----------------------------------------------------------------------------
rm_shutdir() {
  if [ ! -e "$config_fullshutdir" ]; then
    return
  fi
  if $config_keep; then
    echo "name exists: $config_shutdir" >&2
    echo "will not overwrite" >&2
    return 2
  fi
  if [ ! -d "$config_fullshutdir" ]; then
    echo "is not shutdir: $config_shutdir" >&2
    echo "will not overwrite" >&2
    return 2
  fi
  rm -r -- "$config_fullshutdir" > /dev/null 2>&1 || {
    echo "error deleting $config_fullshutdir" >&2
    echo "cannot continue" >&2
    return 3
  }
}

# -----------------------------------------------------------------------------
mkdir_shutdir() {
  mkdir -p -- "$config_fullshutdir" > /dev/null 2>&1 || {
    echo "error creating directory $config_fullshutdir" >&2
    echo "cannot continue" >&2
    return 3
  }
}

cp_tests_shutdir() {
  cp -- tests "$config_fullshutdir" > /dev/null 2>&1 || {
    echo "error copying tests to $config_fullshutdir" >&2
    echo "cannot continue" >&2
    return 3
  }
}

cd_shutdir() {
  cd -- "$config_fullshutdir" > /dev/null 2>&1 || {
    echo "error changing directory to $config_fullshutdir" >&2
    echo "cannot continue" >&2
    return 3
  }
}

# -----------------------------------------------------------------------------
mkdir_logdir() {
  mkdir logdir > /dev/null 2>&1 || {
    echo "error creating logdir" >&2
    return 3
  }
}

cd_logdir() {
  cd logdir > /dev/null 2>&1 || {
    echo "error changing directory to logdir" >&2
    return 3
  }
}

# -----------------------------------------------------------------------------
mkdir_testdir() {
  local testname="$1"
  mkdir -p -- "$testname" > /dev/null 2>&1 || {
    echo "error creating testdir" >&2
    return 3
  }
}

cd_testdir() {
  local testname="$1"
  cd -- "$testname" > /dev/null 2>&1 || {
    echo "error changing directory to testdir" >&2
    return 3
  }
}

# -----------------------------------------------------------------------------
mkdir_workdir() {
  mkdir workdir > /dev/null 2>&1 || {
    echo "error creating workdir" >&2
    return 3
  }
}

cd_workdir() {
  cd workdir > /dev/null 2>&1 || {
    echo "error changing directory to workdir" >&2
    return 3
  }
}

# -----------------------------------------------------------------------------
runtest() {
  local fulltestname="$1"
  (
    export SHUT_PWD
    export SHUT_TEST="$fulltestname"
    exec 0<&- 2>&3 3>&-
    "$fulltestname"
  )
}

runtestsaveexitstatus() {
  local fulltestname="$1"
  runtest "$fulltestname"
  local exitstatus=$?
  echo "$exitstatus" > ../exitstatus
}

runtestsaveoutputsplit() {
  local fulltestname="$1"
  runtestsaveexitstatus "$fulltestname" > ../stdout 3> ../stderr
}

runtestsaveoutputmerge() {
  local fulltestname="$1"
  runtestsaveexitstatus "$fulltestname" > ../output 3>&1
}

# -----------------------------------------------------------------------------
runtestinworkdir() {
  local fulltestname="$1"
  mkdir_workdir || return
  (
    cd_workdir || return
    $runtestsaveoutput_func "$fulltestname"
  )
}

# -----------------------------------------------------------------------------
printheader() {
  local statusstring="$1"
  local testname="$2"
  echo "================"
  echo "$statusstring $testname"
}

printexitstatus() {
  local exitstatus="$1"
  echo "exitstatus: $exitstatus"
}

printbodysplit() {
  echo "stdout:"
  cat stdout | tail -n "$config_tail" | sed 's/^/  /'
  echo "stderr:"
  cat stderr | tail -n "$config_tail" | sed 's/^/  /'
}

printbodymerge() {
  echo "output:"
  cat output | tail -n "$config_tail" | sed 's/^/  /'
}

printreportpass() {
  local testname="$1"
  printheader "PASS" "$testname"
  $printbody_func
}

printreportfail() {
  local testname="$1"
  local exitstatus="$2"
  printheader "FAIL" "$testname"
  printexitstatus "$exitstatus"
  $printbody_func
}

printreport() {
  local testname="$1"
  local exitstatus="$(cat exitstatus)"
  if [ 0 -eq "$exitstatus" ]; then
    echo "$testname" >> "$config_fullshutdir/pass"
    $printreportpass_func "$testname"
  else
    echo "$testname" >> "$config_fullshutdir/fail"
    $printreportfail_func "$testname" "$exitstatus"
  fi
}

# -----------------------------------------------------------------------------
runtestandprintreport() {
  local testname="$1"
  local fulltestname="$2"
  runtestinworkdir "$fulltestname" || return
  printreport "$testname"
}

# -----------------------------------------------------------------------------
runtestintestdir() {
  local testname="$1"
  local fulltestname="$2"
  mkdir_testdir "$testname" || return
  (
    cd_testdir "$testname" || return
    runtestandprintreport "$testname" "$fulltestname"
  )
}

# -----------------------------------------------------------------------------
runtestifexecutable() {
  local testname="$1"
  local fulltestname="$SHUT_PWD/${testname#./}"
  [ -x "$fulltestname" ] || {
    echo "not found or not executable: $testname" >&2
    return 3
  }
  runtestintestdir "$testname" "$fulltestname"
}

# -----------------------------------------------------------------------------
runtestcatchterror() {
  runtestifexecutable "$@" 2> "$config_tempdir/lasterror" || {
    echo "$testname" >> "$config_fullshutdir/error"
    printheader "ERROR" "$testname"
    cat "$config_tempdir/lasterror"
  }
}

# -----------------------------------------------------------------------------
runtests() {
  touch ../pass ../fail ../error
  local testname
  while read -r testname; do
    runtestcatchterror "$testname"
  done < ../tests
}

# -----------------------------------------------------------------------------
runtestsinlogdir() {
  mkdir_logdir || return
  (
    cd_logdir || return
    runtests
  )
}

# -----------------------------------------------------------------------------
printlist() {
  local listname="$1"
  echo "================"
  echo "$listname:"
  cat "$listname"
}

printcounts() {
  wc -l tests pass fail error | {
    read -r runcount ignorefilename
    read -r passcount ignorefilename
    read -r failcount ignorefilename
    read -r errorcount ignorefilename
    read -r ignoretotal
    echo "================"
    printf "run: %d pass: %d fail: %d error: %d\n" \
          "$runcount" "$passcount" "$failcount" "$errorcount"
  }
}

printsummary() {
  if [ -s fail ]; then
    printlist fail
  fi
  if [ -s error ]; then
    printlist error
  fi
  printcounts
}

# -----------------------------------------------------------------------------
determineexitstatus() {
  [ ! -s fail ] && [ ! -s error ] # exitstatus based on list empty or not
}

runtestsandprintsummary() {
  runtestsinlogdir || return
  printsummary
  determineexitstatus
}

runtestsinshutdir() {
  rm_shutdir || return
  mkdir_shutdir || return
  cp_tests_shutdir || return
  (
    cd_shutdir || return
    runtestsandprintsummary
  )
}

# -----------------------------------------------------------------------------
runtestscatcherror() {
  runtestsinshutdir 2> "$config_tempdir/runtestserror"
  exitstatus=$?
  [ -s "$config_tempdir/runtestserror" ] && {
    cat "$config_tempdir/runtestserror" >&2
  }
  return "$exitstatus"
}

printtestnames() {
  cat tests
  local count=$(wc -l < tests)
  echo "================"
  echo "would run: $count"
}

workiftestsfound() {
  [ -s tests ] || {
    echo "no tests found"
    return 2
  }
  $work_func
}

collectnamesandwork() {
  collecttestnames
  workiftestsfound
}

configthenwork() {
  configfromargv "$@"
  setup
  collectnamesandwork
}

# -----------------------------------------------------------------------------
rm_tempdir() {
  rm -r -- "$config_tempdir" > /dev/null 2>&1 || {
    echo "error deleting tempdir" >&2
    echo "not fatal but annoying" >&2
    return 3
  }
}

# -----------------------------------------------------------------------------
workintempdir() {
  mktemp_tempdir || return
  (
    cd_tempdir || return
    configthenwork "$@"
  )
  local exitstatus=$?
  rm_tempdir || return
  return "$exitstatus"
}

# -----------------------------------------------------------------------------
workcatcherror() {
  workintempdir "$@"
}

# -----------------------------------------------------------------------------
main() {
  workcatcherror "$@"
}

main "$@"
